export const MenuList = [
  {title: 'Home',
  url: '/'},
  {title: 'Top Contributors',
  url: '/top-contributors'},
  {title: 'Ideas',
  url: '/ideas'},
  {title: 'Account',
  url: '/account'},
  {title: 'Support',
  url: '/support'},
  {title: 'Sign Up',
  url: '/sign-up'},
  {title: 'Sign In',
  url: '/sign-in'},
]